Initialize project with serverless framework
ntuscse/be pull request #4
Opened 2022-02-01 11:37 UTC by RealDyllon

Resolves #1 
Resolves #3

2022-02-01 12:25 UTC, RealDyllon commented
@tayalaks2001 Anything missing from this PR?

2022-02-01 14:11 UTC, tayalaks2001 commented
> @tayalaks2001 Anything missing from this PR?

Nope, all good!

2022-02-03 03:17 UTC, cyiafn commented
Reviewer can approve merge also esp if tests pass

2022-02-03 03:52 UTC, RealDyllon commented
@tayalaks2001 mind updating the readme?

2022-02-03 14:28 UTC, tayalaks2001 commented
@RealDyllon updated the docs, I think this PR is ok to be merged now!

2022-02-03 15:26 UTC, RealDyllon commented
@yankai14 could you review this PR? cheers

2022-02-03 15:39 UTC, yankai14 requested changes

2022-02-03 15:39 UTC, yankai14 commented on be/api/v1/templates/nonAuthRoute.py
> +    stage = os.environ.get('STAGE', 'dev')  # ???
Remove the comment?

2022-02-03 15:43 UTC, RealDyllon commented on be/api/v1/templates/nonAuthRoute.py
> +    stage = os.environ.get('STAGE', 'dev')  # ???
@yankai14 
Fixed :)

2022-02-04 14:44 UTC, yankai14 approved these changes

2022-02-05 07:10 UTC, merged