Added order table and implementation on post checkout
ntuscse/be pull request #42
Opened 2022-11-19 10:35 UTC by yankai14

2022-11-19 11:08 UTC, chanbakjsd requested changes

2022-11-19 11:08 UTC, chanbakjsd commented on be/api/v1/endpoints/cart/checkout/post.py
> +        transactionID = "payment_intent.id"
Payment intent ID is not being stored correctly.

2022-11-19 11:08 UTC, chanbakjsd commented on utils/dal/order.py
> +        "images": orderItem.images,
Is it necessary to store images in an order?

2022-11-19 11:08 UTC, chanbakjsd commented on utils/dal/order.py
> +        "orderItems": orderItems
```suggestion
        "orderItems": orderItems,
```

2022-11-19 11:08 UTC, chanbakjsd commented on utils/dal/order.py
> +    print(read_item_from_db(table_name, {"orderID": order.orderID}))
Is this `print` necessary?

2022-11-19 12:51 UTC, aryans1204 requested changes
Dynamo DB stuff looks ok, though I noticed the payment intent ID is not stored correctly, as mentioned by @chanbakjsd .

2022-11-19 12:51 UTC, aryans1204 commented on serverless.yml
> +          ReadCapacityUnits: 1
Might want to change read and write capacities to 2 units, since transactional read/writes consume 2 units.

2023-01-12 13:48 UTC, chanbakjsd approved these changes

2023-01-12 13:51 UTC, aryans1204 approved these changes
LGTM 🚀

2023-01-12 13:51 UTC, merged